version: '3.8'

services:
  # Base de datos PostgreSQL
  database:
    image: postgres:15-alpine
    container_name: paint_store_db
    environment:
      POSTGRES_DB: paintstore
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - paint_network

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: paint_store_backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=paintstore
      - DB_USER=admin
      - DB_PASSWORD=password123
    depends_on:
      - database
    networks:
      - paint_network
    restart: unless-stopped

  # Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: paint_store_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - paint_network
    restart: unless-stopped

networks:
  paint_network:
    driver: bridge

volumes:
  postgres_data: